import { NextRequest, NextResponse } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

// GET /api/pdf?title=...&lines=a|b|c
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const title = searchParams.get('title') || 'DiveMix Plan';
  const lines = (searchParams.get('lines') || '').split('|').filter(Boolean);

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  let y = 800;

  const draw = (text: string, size = 12, bold = false) => {
    page.drawText(text, { x: 50, y, size, font, color: rgb(1, 1, 1) });
    y -= size + 8;
  };

  // dark bg
  page.drawRectangle({
    x: 0,
    y: 0,
    width: 595.28,
    height: 841.89,
    color: rgb(0.06, 0.07, 0.12),
  });

  draw(title, 18);
  draw('— Generated by DiveMix', 10);

  y -= 6;
  lines.forEach((l) => draw(l, 12));

  const bytes = await pdf.save();
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="divemix-plan.pdf"`,
    },
  });
}
