import { NextRequest } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export const runtime = 'nodejs'; // Serverless/Node
export const dynamic = 'force-dynamic'; // no caching

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const title = searchParams.get('title') || 'DiveMix Plan';
  const lines = (searchParams.get('lines') || '').split('|').filter(Boolean);

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);

  // dark background
  page.drawRectangle({
    x: 0,
    y: 0,
    width: 595.28,
    height: 841.89,
    color: rgb(0.06, 0.07, 0.12),
  });

  let y = 800;
  const draw = (text: string, size = 12) => {
    page.drawText(text, { x: 50, y, size, font, color: rgb(1, 1, 1) });
    y -= size + 8;
  };

  draw(title, 18);
  draw('— Generated by DiveMix', 10);
  y -= 6;
  lines.forEach((l) => draw(l, 12));

  // pdf-lib gives Uint8Array; copy to guarantee a plain ArrayBuffer (no SAB union)
  const bytes = await pdf.save(); // Uint8Array
  const copy = new Uint8Array(bytes.length);
  copy.set(bytes);
  const ab: ArrayBuffer = copy.buffer; // <- definitely ArrayBuffer

  return new Response(ab, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="divemix-plan.pdf"',
      'Cache-Control': 'no-store',
    },
  });
}
